#!/usr/bin/env bash

if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z $ebs_loc ]]; then
    # Try automatically building ember-shared
    mkdir .buildsystem-temp
    (
        cd .buildsystem-temp
        git clone --depth 1 https://github.com/ethus3h/ember-shared.git
        cd ember-shared
        make autodep
        ./configure
        make
        make install || true
    )
fi

# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

((EUID)) && exec sudo -- "$0" "$@"

source support/getDirs

failinstall() {
    die "ERROR: Could not find or install $1."
}

cd "$(getSystemTempLocation)" || die

#### End of automatic dependency installation install script template ####

# Any extra automatic dependency installation goes here.
