#!/usr/bin/env bash
# This file should be sourced rather than run directly.

#NOTE: MAINTENANCE: Manual error printing
if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
    printf '%b' '\033[1;31m' >&2
    echo "ERROR: ember-shared is not properly installed! It must be installed before installing $packageName." >&2
    printf '%b' '\033[0m' >&2
    exit 1
fi

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

packageName="$1"
shift

overrideInstalledAppDataDir="/usr/share"
overrideInstalledAppDataDirArg="${1#*=}"
if [[ "$1" == "--override-data-dir"* ]] && [[ -n "$overrideInstalledAppDataDirArg" ]]; then
    overrideInstalledAppDataDir="$overrideInstalledAppDataDirArg"
fi
shift

{ emberPrefix="$(<support/.prefix)" || true; } 2> /dev/null
{ emberMandir="$(<support/.mandir)" || true; } 2> /dev/null
{ emberInfodir="$(<support/.infodir)" || true; } 2> /dev/null
{ emberDatadir="$(<support/.datadir)" || true; } 2> /dev/null
{ emberSysconfdir="$(<support/.sysconfdir)" || true; } 2> /dev/null
{ emberLocalstatedir="$(<support/.localstatedir)" || true; } 2> /dev/null

#echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
if [[ -z "$emberDestdir" ]] && [[ -n "$1" ]]; then
    emberDestdir="$1"
    shift
fi
if [[ -z "$emberPrefix" ]] && [[ -n "$1" ]]; then
    emberPrefix="$1"
    shift
fi
if [[ -z "$emberCapPrefix" ]] && [[ -n "$1" ]]; then
    emberCapPrefix="$1"
    shift
fi
if [[ -z "$emberExecPrefix" ]] && [[ -n "$1" ]]; then
    emberExecPrefix="$1"
    shift
fi
if [[ -z "$emberBindir" ]] && [[ -n "$1" ]]; then
    emberBindir="$1"
    shift
fi
if [[ -z "$emberDatarootdir" ]] && [[ -n "$1" ]]; then
    emberDatarootdir="$1"
    shift
fi
if [[ -z "$emberDatadir" ]] && [[ -n "$1" ]]; then
    emberDatadir="$1"
    shift
fi
if [[ -z "$emberSysconfdir" ]] && [[ -n "$1" ]]; then
    emberSysconfdir="$1"
    shift
fi
if [[ -z "$emberSharedstatedir" ]] && [[ -n "$1" ]]; then
    emberSharedstatedir="$1"
    shift
fi
if [[ -z "$emberPrefix" ]]; then
    if [[ -z "$emberCapPrefix" ]]; then
        emberPrefix=/usr/local
    else
        emberPrefix="$emberCapPrefix"
    fi
fi
emberPrefix="$emberDestdir$emberPrefix"
#echo "emberPrefix: $emberPrefix"
if [[ -z "$emberExecPrefix" ]]; then
    emberExecPrefix="$emberPrefix"
else
    emberExecPrefix="$emberDestdir$emberExecPrefix"
fi
#echo "emberExecPrefix: $emberExecPrefix"
if [[ -z "$emberBindir" ]]; then
    emberBindir="$emberExecPrefix"/bin
fi
#echo "emberBindir: $emberBindir"
if [[ -z "$emberDatarootdir" ]]; then
    emberDatarootdir="$emberPrefix"/share
fi
#echo "emberDatarootdir: $emberDatarootdir"
if [[ -z "$emberDatadir" ]]; then
    emberDatadir="$emberDestdir$emberDatarootdir"
else
    emberDatadir="$emberDestdir$emberDatadir"
fi
#echo "emberDatadir: $emberDatadir"
if [[ -z "$emberSysconfdir" ]]; then
    emberSysconfdir="$emberPrefix"/etc
else
    emberSysconfdir="$emberPrefix$emberSysconfdir"
fi
#echo "emberSysconfdir: $emberSysconfdir"
if [[ -z "$emberSharedstatedir" ]]; then
    emberSharedstatedir="$emberPrefix"/var
else
    emberSharedstatedir="$emberPrefix$emberSharedstatedir"
fi
#echo "emberSharedstatedir: $emberSharedstatedir"

emberEmberdir="$emberPrefix"/Ember\ Library

# Done setting up variables
