#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

packageName="$1"
shift

# Note: Only provide this file if the package should run on macOS. Your code may require some
# changes to be correctly transformed by this script.

fail() {
    #NOTE: MAINTENANCE: Manual error printing
    if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
        printf '%b' '\033[1;31m' >&2
        echo "ERROR: ember-shared is not properly installed! It must be installed before installing $packageName." >&2
        printf '%b' '\033[0m' >&2
        exit 1
    fi
}

if [[ "$OSTYPE" = darwin* ]]; then
    if ! type "greadlink"; then
        fail
    fi
    if ! type "ember_bash_setup"; then
        fail
    fi
    if [[ -e "scripts" ]]; then
        find scripts -type f -exec perl -0777 -p -i -e 's/readlink /greadlink /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/dirname /gdirname /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/sort /gsort /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/stdbuf /gstdbuf /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/sha256sum /gsha256sum /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/sha512sum /gsha512sum /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/ncdu /8731d097a5ed41149c7ffb67756c310e /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/du /gdu /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/8731d097a5ed41149c7ffb67756c310e /ncdu /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/sed /gsed /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/find /gfind /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/stat /gstat /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/wc /gwc /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/mktemp /gmktemp /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/split /gsplit /g' {} \;
        find scripts -type f -exec perl -0777 -p -i -e 's/tar /gtar /g' {} \;
    fi
fi
