function post_pkg_postinst() {
    if test "$CATEGORY/$PN" = "sys-kernel/wreathe-kernel"; then
        emerge @module-rebuild
		grub-mkconfig -o /boot/grub/grub.cfg && elog "Updated /boot/grub/grub.cfg"
		dosym /boot/grub/grub.cfg /boot/grub/grub.conf
		# Send notification about kernel update to users
		(
			getent passwd | while IFS=: read -r name password uid gid gecos home shell; do
				top="${home#/}"
				top="${top%%/*}"
				case $top in
					bin|dev|etc|lib*|no*|proc|sbin|usr|var)
						# probably not a human, so don't bother notfiying
						true
						;;
					*)
						DISPLAY=:0 sudo -u "$name" bash -c 'DISPLAY=:0 notify-send "Kernel update installed" "A kernel update has been installed. A system administrator can reboot the computer to use the new kernel."'
						;;
				esac
			done
		)
    fi
}
