#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

# Updates the keyboard layout settings.

# Apply changes to file
sudo cp /usr/share/X11/xkb/symbols/us /tmp/wreathe-settings_keymap-apply.tmp
xkbUsSymbolsKnownChecksum="$(grep /usr/share/X11/xkb/symbols/us /var/db/pkg/x11-misc/xkeyboard-config-*/CONTENTS | awk '{print $(NF-1)}')"
xkbUsSymbolsRealChecksum="$(md5sum /usr/share/X11/xkb/symbols/us | awk '{print $1}')"
if [[ "$xkbUsSymbolsRealChecksum" == "$xkbUsSymbolsKnownChecksum" ]]; then
    # Keymap file has not been modified by this script
    sudo cat /Wreathe/.Resources/Keymaps/wreathe >> /usr/share/X11/xkb/symbols/us
fi
# Read and apply settings
(
    cd /etc/wreathe/keyboard/mapping/
    geometry="$(<geometry)"
    layout="$(<layout)"
    variant="$(<variant)"
    wreathe="$(<use_wreathe_layout)"
    if [[ "$wreathe" == "true" ]]; then
        variant="wreathe-$layout"
        layout="us"
    fi
    setxkbmap -v 10 "$layout" "$variant"
    sudo localectl set-x11-keymap "$layout" "$geometry" "$variant"
)
