#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

# Only if needed: ((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

packageToPackage="$1"

function buildPackages() {
    path="$(equery w "$1")"
    ebuild "$path" rpm
    packageName="$(dirname "$path")"
    categoryName="$(dirname "$packageName")"
    packageName="$(basename "$packageName")"
    categoryName="$(basename "$categoryName")"
    ebuildName="$(basename "$path")"
    ebuildName="${ebuildName%.ebuild}"
    rpmPath=/var/tmp/portage/"$categoryName"/"$ebuildName"/temp/rpmbuild/RPMS/x86_64/
    rpmFile="$(find "$rpmPath" -type f -print -and -quit)"
    rpmName="$(basename "$rpmFile")"
    mv "$rpmFile" ./rpm-output/
    cp ./rpm-output/"$rpmName" ./deb-output/
    (
    cd ./deb-output/
    alien --to-deb "./$rpmName"
    rm "./$rpmName"
    )
}

targets=(emerald-themes)
targetCount="${#targets[@]}"
(
cd ~
mkdir -p ember-wreathe-packages/rpm-output
mkdir -p ember-wreathe-packages/deb-output
cd ember-wreathe-packages
if [[ -n "$packageToPackage" ]]; then
    for (( i=0; i<targetCount; i++ )); do
        buildPackages "${targets[$i]}"
    done
else
    buildPackages "$packageToPackage"
fi
)
