#!/usr/bin/env bash
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR

apt-get update
apt-get --yes upgrade
apt-get --yes install aptitude git ranger python3-pip
apt-get --yes remove compiz compiz-bcop compiz-core compiz-dev compiz-gnome compiz-mate compiz-plugins compiz-plugins-default compiz-plugins-experimental compiz-plugins-extra compiz-plugins-main compizconfig-settings-manager libcompizconfig0 libcompizconfig0-dev python-compizconfig
git clone https://github.com/ethus3h/crystallize.git
(
    cd crystallize
    make autodep
)
pip3 install internetarchive
mkdir -p /var/ember-wreathe-packages-repository
cd /var/ember-wreathe-packages-repository
ia download Wreathe-GNU-Linux-Multisystem-Packages --glob='*.deb' || { echo "Could not fetch packages."; exit 1 }
dpkg -i ./Wreathe-GNU-Linux-Multisystem-Packages/Wreathe-GNU-Linux-Multisystem-Packages/deb-output/*.deb
