#!/usr/bin/env bash
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR

packageToPackage="$1"

# shellcheck disable=SC1091
source ./targets &> /dev/null

function buildPackages() {
    getPackageData "$1"
    echo "Downloading DEB for $packageAtom..."
    dpkg -i 
    
    emerge --pkg-format "rpm" --buildpkgonly "$packageAtom"
    rpmPath=/usr/portage/rpm/"$categoryName"/
    rpmFile="$(find "$rpmPath" -name "$ebuildName"'*' -type f -print -and -quit)"
    rpmName="$(basename "$rpmFile")"
    cp "$rpmFile" ./rpm-output/
    echo "Making DEB for $packageAtom..."
    cp ./rpm-output/"$rpmName" ./deb-output/
    (
        cd ./deb-output/
        alien --to-deb "./$rpmName"
        rm "./$rpmName"
    )
}

pip install internetarchive

(
    mkdir -p /var/ember-wreathe-packages-repository
    cd /var/ember-wreathe-packages-repository
    ia download Wreathe-GNU-Linux-Multisystem-Packages --glob='*.deb'
    dpkg -i ./Wreathe-GNU-Linux-Multisystem-Packages/*.deb
)
