#!/usr/bin/env bash
# shellcheck disable=SC1091
#set -x

targets=(
    crystallize
    ember-shared
    futuramerlin-web-toolkit
    wreathe-backgrounds
    wreathe-base
    wreathe-typeface-family
    wreathe-typefaces-redist

    kde-frameworks/kdelibs:4
    kde-apps/libkonq:4
    kdebase-kioslaves
    kde-apps/dolphin:4
    dev-qt/qtcore:4
    dev-qt/qtgui:4
    dev-qt/qtscript:4

    dev-python/compizconfig-python
    x11-apps/compiz-boxmenu
    x11-apps/compiz-manager
    x11-apps/fusion-icon
    x11-libs/compiz-bcop
    x11-libs/libcompizconfig
    x11-misc/ccsm
    x11-misc/compiz-debug-utils
    x11-misc/simple-ccsm
    x11-plugins/compicc
    x11-plugins/compiz-extra-snowflake-textures
    x11-plugins/compiz-plugins-community
    x11-plugins/compiz-plugins-experimental
    x11-plugins/compiz-plugins-extra
    x11-plugins/compiz-plugins-main
    x11-plugins/compiz-plugins-meta
    x11-themes/emerald-themes
    x11-wm/compiz
    x11-wm/compiz-meta
    x11-wm/emerald
)
targetCount="${#targets[@]}"

function getPackageData() {
    packageAtom="$1"
    packagePath="$(equery w "$packageAtom")"
    packageName="$(dirname "$packagePath")"
    categoryName="$(dirname "$packageName")"
    packageName="$(basename "$packageName")"
    categoryName="$(basename "$categoryName")"
    ebuildName="$(basename "$path")"
    ebuildName="${ebuildName%.ebuild}"
}
