#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

packageToPackage="$1"

# shellcheck disable=SC1091
source ./targets &> /dev/null

function buildPackages() {
    getPackageData "$1"
    echo "Uploading RPM for $1..."
    rpmPath=./rpm-output/
    rpmFile="$(find "$rpmPath" -name "$ebuildName"'*' -type f -print -and -quit)"
    ia uplo
    rpmName="$(basename "$rpmFile")"
    cp "$rpmFile" ./rpm-output/
    echo "Making DEB for $1..."
    cp ./rpm-output/"$rpmName" ./deb-output/
    (
        cd ./deb-output/
        alien --to-deb "./$rpmName"
        rm "./$rpmName"
    )
}

(
    cd /home/kyan/
    mkdir -p ./ember-wreathe-packages/rpm-output/temp
    mkdir -p ./ember-wreathe-packages/deb-output
    (
        cd ember-wreathe-packages
        if [[ -z "$packageToPackage" ]]; then
            for (( i=0; i<targetCount; i++ )); do
                buildPackages "${targets[$i]}"
            done
        else
            buildPackages "$packageToPackage"
        fi
    )
    chown -R kyan:kyan ./ember-wreathe-packages/rpm-output
    chown -R kyan:kyan ./ember-wreathe-packages/deb-output
)
