#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

packageToPackage="$1"

# shellcheck disable=SC1091
source ./targets &> /dev/null

scriptDir="$(pwd)"

(
    cd /home/kyan/
    cd ./ember-wreathe-packages
    #find . -name '*.deb' -or -name '*.rpm' -exec "$scriptDir"/upload-single {} \;
    find . -name '*.deb' -exec "$scriptDir"/upload-single {} \;
)
